### ISSUE TITLE
[BUG] Device orientation will convert to UNKNOWN during screen rotation when not match Orientation

### ISSUE THREAD

**Issue by Hiroenzo** [gladiuscode/react-native-orientation-director#23]
**Describe the bug**
Device orientation will convert to `UNKNOWN` during screen rotation when not match `Orientation`.

**To Reproduce**
1. Rotate screen.
2. When the angle of screen rotation does not match `PORTRAIT` `LANDSCAPE_RIGHT` `PORTRAIT_UPSIDE_DOWN` or `LANDSCAPE_LEFT`.
3. Device orientation will convert to `UNKNOWN`.

**Expected behavior**
If device orientation is not match `Orientation` then use the last device orientation.

**Screenshots**

https://github.com/user-attachments/assets/6abbf55d-d3a7-4f8b-978d-9d158b807493

Logcat:
<img width="328" alt="image" src="https://github.com/user-attachments/assets/f5d1f7b4-a9e6-4ca8-8ed0-53b3691b5352">

**Smartphone (please complete the following information):**
 - OS: Android
 - Device: Huawei P30
 - Version 10

**Comment by gladiuscode** [comment]
Hi @Hiroenzo,
I've looked into it a little bit more and if I've understood it correctly, this happens because:

> [ORIENTATION_UNKNOWN](https://developer.android.com/reference/android/view/OrientationEventListener#ORIENTATION_UNKNOWN) is returned when the device is close to flat and the orientation cannot be determined.

from: https://developer.android.com/reference/android/view/OrientationEventListener#onOrientationChanged(int)

We've implemented this listener to track the device orientation, but it does fails in certain cases and currently this library overrides the previous detected orientation with the newest one as soon as we get a new one, without caring about whether it was matching a valuable one such as Portrait or Landscape.

Looking into the others libraries code I can see that they compute the orientation value using [Sensors](https://developer.android.com/develop/sensors-and-location/sensors/sensors_overview).
I wonder if we should do the same and actually track when the device orientation is flat or flat and upside down. I'll look into it when I have time and I'll try to understand if we actually need to provide such behavior.

Meanwhile we can `patch` it with your code and avoid an override when the device orientation cannot be computed and results into an UNKNOWN.

Did you check on iOS? Does it behave the same?

**Comment by gladiuscode** [comment]
> Did you check on iOS? Does it behave the same?

I've played a lil bit using the example app and it does work on iOS, i had forgotten that on iOS we actually have the face up and face down orientations available. 😅

**Comment by Hiroenzo** [comment]
> Hi @Hiroenzo, I've looked into it a little bit more and if I've understood it correctly, this happens because:
> 
> > [ORIENTATION_UNKNOWN](https://developer.android.com/reference/android/view/OrientationEventListener#ORIENTATION_UNKNOWN) is returned when the device is close to flat and the orientation cannot be determined.
> 
> from: https://developer.android.com/reference/android/view/OrientationEventListener#onOrientationChanged(int)
> 
> We've implemented this listener to track the device orientation, but it does fails in certain cases and currently this library overrides the previous detected orientation with the newest one as soon as we get a new one, without caring about whether it was matching a valuable one such as Portrait or Landscape.
> 
> Looking into the others libraries code I can see that they compute the orientation value using [Sensors](https://developer.android.com/develop/sensors-and-location/sensors/sensors_overview). I wonder if we should do the same and actually track when the device orientation is flat or flat and upside down. I'll look into it when I have time and I'll try to understand if we actually need to provide such behavior.
> 
> Meanwhile we can `patch` it with your code and avoid an override when the device orientation cannot be computed and results into an UNKNOWN.
> 
> Did you check on iOS? Does it behave the same?

Thank you for your answer. It works perfectly on iOS.
